<?php

require_once dirname(__FILE__) . '/includes/css.inc';
require_once dirname(__FILE__) . '/includes/scripts.inc';
require_once dirname(__FILE__) . '/includes/scripts-experimental.inc';

/**
  * Implements hook_form_alter
  */
function magic_form_system_theme_settings_alter(&$form, &$form_state) {

  $theme = $form_state['build_info']['args'][0];

  $form['#submit'][] = 'magic_system_theme_settings_submit';

  $form['magic_performance'] = array(
    '#type' => 'vertical_tabs',
    '#attached' => array(
      'css' => array(drupal_get_path('module', 'magic') . '/css/magic.admin.css'),
    ),
    '#weight' => 100,
  );

  // CSS
  $form['magic_performance']['css'] = array(
    '#type' => 'fieldset',
    '#title' => t('CSS Enhancements'),
  );

  $form['magic_performance']['css']['magic_embedded_mqs'] = array(
    '#type' => 'checkbox',
    '#title' => t('Embed Media Queries'),
    '#description' => t('Embed media queries instead of attaching them to the <pre>&lt;link&gt;</pre> tags, reducing the number of separate CSS aggregates.'),
    '#default_value' => variable_get($theme . '-magic_embedded_mqs'),
  );

  $form['magic_performance']['css']['magic_css_excludes'] = array(
    '#type' => 'textarea',
    '#title' => t('Exclude CSS files'),
    '#description' => t("Enter one file per line. The <pre>*</pre> character is a wildcard to match all similar items, for instance <pre>system/*.css</pre> will remove all CSS provided by the System module. The <pre>~</pre> character is a reserved character to keep all similar items if they would otherwise be removed, for instance <pre>~system/system.menus.css</pre> to keep System module's menu CSS even if we remove the rest of System module's CSS. You may use <pre>:all</pre> to target all CSS files, <pre>:core</pre> to target all Core provided CSS files, <pre>:contrib</pre> to target all Contrib provided CSS files, <pre>:base-theme</pre> to target all base theme provided CSS files, and <pre>:current-theme</pre> to target all CSS files provided by the current theme."),
    '#default_value' => implode("\n", (array) variable_get($theme . '-magic_css_excludes', array())),
  );

  // JavaScript
  $form['magic_performance']['js'] = array(
    '#type' => 'fieldset',
    '#title' => t('JavaScript Enhancements'),
  );


  $form['magic_performance']['js']['magic_footer_js'] = array(
    '#type' => 'checkbox',
    '#title' => t('Move JavaScript to the Footer'),
    '#description' => t("Will move all JavaScript to the bottom of your page. This can be overridden on an individual basis by setting the <pre>'force header' => true</pre> option in <pre>drupal_add_js</pre> or by using <pre>hook_js_alter</pre> to add the option to other JavaScript files. Settings will always stay in the head."),
    '#default_value' => variable_get($theme . '-magic_footer_js'),
  );

  $form['magic_performance']['js']['magic_library_head'] = array(
    '#type' => 'checkbox',
    '#title' => t('Keep Libraries in the Head'),
    '#description' => t("If you have JavaScript inline in the body of your document, such as if you are displaying ads, you may need to keep Drupal JS Libraries in the head instead of moving them to the footer. This will keep Drupal libraries in the head while still moving all other JavaScript to the footer."),
    '#default_value' => variable_get($theme . '-magic_library_head'),
    '#states' => array(
      'visible' => array(
        ':input[name=magic_footer_js]' => array('checked' => TRUE),
      ),
    ),
  );

  $form['magic_performance']['js']['magic_experimental_js'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use Experimental JavaScript Handling'),
    '#description' => t("This will enable additional options for JavaScript, including browser options, <pre>async</pre> and <pre>defer</pre> attributes, and optional additional attributes."),
    '#default_value' => variable_get($theme . '-magic_experimental_js'),
  );

  $form['magic_performance']['js']['magic_js_excludes'] = array(
    '#type' => 'textarea',
    '#title' => t('Exclude JavaScript files'),
    '#description' => t("Enter one file per line. The <pre>*</pre> character is a wildcard to match all similar items, for instance <pre>overlay/*.js</pre> will remove all JS provided by the Overlay module. The <pre>~</pre> character is a reserved character to keep all similar items if they would otherwise be removed, for instance <pre>~overlay/overlay-child.js</pre> to keep Overlay module's overlay-child JS even if we remove the rest of Overlay module's JS. You may use <pre>:all</pre> to target all JS files, <pre>:core</pre> to target all Core provided JS files, <pre>:contrib</pre> to target all Contrib provided JS files, <pre>:base-theme</pre> to target all base theme provided JS files, and <pre>:current-theme</pre> to target all JS files provided by the current theme."),
    '#default_value' => implode("\n", (array) variable_get($theme . '-magic_js_excludes', array())),
  );

}

function magic_system_theme_settings_submit($form, &$form_state) {
  $theme = $form_state['build_info']['args'][0];
  $options = array(
    'magic_js_excludes',
    'magic_experimental_js',
    'magic_library_head',
    'magic_footer_js',
    'magic_css_excludes',
    'magic_embedded_mqs',
  );

  foreach ($options as $option) {
    $value = $form_state['input'][$option];
    $variable = $theme . '-' . $option;
    if ($value != NULL || variable_get($variable) != $value) {
      if ($option == 'magic_js_excludes' || $option == 'magic_css_excludes') {
        $value = explode("\n", $value);
      }
      variable_set($variable, $value);
    }
  }
}

/**
  * Implements hook_theme_registry_alter().
  */
function magic_theme_registry_alter(&$registry) {
  if (($index = array_search('template_process_html', $registry['html']['process functions'], TRUE)) !== FALSE) {
    array_splice($registry['html']['process functions'], $index, 1, 'magic_template_process_html_override');
  }
}

/**
  * Overrides template_process_html() in order to provide support for awesome new stuffzors!
  *
  * Huge, amazing ups to the wizard Sebastian Siemssen (fubhy) for showing me how to do this.
  */
function magic_template_process_html_override(&$variables) {
  // dpm($variables);

  global $theme_key;

  $options = array(
    'magic_js_excludes',
    'magic_experimental_js',
    'magic_library_head',
    'magic_footer_js',
    'magic_css_excludes',
    'magic_embedded_mqs',
  );
  $theme_options = array();

  foreach ($options as $option) {
    $theme_options[$option] = variable_get($theme_key . '-' . $option);
  }

  // Render page_top and page_bottom into top level variables.
  $variables['page_top'] = drupal_render($variables['page']['page_top']);
  $variables['page_bottom'] = drupal_render($variables['page']['page_bottom']);
  // Place the rendered HTML for the page body into a top level variable.
  $variables['page'] = $variables['page']['#children'];


  $variables['head'] = drupal_get_html_head();
  $variables['css'] = drupal_add_css();
  $variables['styles']  = drupal_get_css();

  if ($theme_options['magic_experimental_js']) {
    dpm('Experimental JS');
    $variables['scripts'] = drupal_get_js();
  }
  elseif ($theme_options['magic_footer_js']) {
    $variables['page_bottom'] .= magic_get_js('footer');
    $variables['scripts'] = magic_get_js('header');
  }
  else {
    dpm('Normal JS');
    $variables['scripts'] = drupal_get_js();
  }
}